#!/bin/bash

set -euo pipefail

if [ "$#" -lt "1" ]
then
  SCRIPT_NAME=$(basename "${0}")
  echo "Usage: ${SCRIPT_NAME} https://github.com/account/repo"
  exit 1
fi

GITHUB_PATH="${HOME}/Code/git/"
REPO_URL="${1}"


if [[ "${REPO_URL}" =~ ".." ]]; then
  # Poor man's path traversal mitigation.
  echo -- "Invalid URL: ${REPO_URL}"
  exit 1
fi

if [[ "${REPO_URL}" =~ ^https:// ]]; then
  URL_PATH=${REPO_URL#"https://"}
  REPO=${URL_PATH%".git"}
  IFS="/"
  read -a PARTS <<< "${REPO}"
  REPO_PATH="${PARTS[0]}/${PARTS[1]}"

  FOLDER="${GITHUB_PATH}/${REPO_PATH}"
  mkdir -p "${FOLDER}"
  cd "${FOLDER}"
  open "${FOLDER}"
  code "${FOLDER}"
  if [ -f ".git" ] || [ -d ".git" ]
  then
    echo -- "Already checked out."
  else 
     git clone "https://${REPO_PATH}" .
  fi
else
  echo -- "Invalid URL: ${REPO_URL}"
fi
