#!/bin/bash

set -euo pipefail

HASH="$(git rev-parse HEAD)"
# TODO: This requires depot_tools or https://github.com/lgarron/git-freeze
git freeze
git update-ref refs/last-freeze HEAD
git log --pretty=oneline "$HASH...HEAD"
git reset --hard "$HASH"
