#!/usr/bin/env fish

set REALPATH (realpath $argv[1])
if string match "$HOME/Dropbox (Maestral)/*" $REALPATH
    set DROPBOX_PATH (string replace "$HOME/Dropbox (Maestral)/" "" $REALPATH)
    open "https://www.dropbox.com/home/$MAESTRAL_PATH"
else
    echo "Not in the Maestral Dropbox folder: $REALPATH"
end
