#!/bin/bash

set -euo pipefail

if [ "$#" -lt "1" ]
then
  SCRIPT_NAME=$(basename "${0}")
  echo "Usage: ${SCRIPT_NAME} in-file.anything [out-file.wav]"
  exit 1
fi

IN_FILE="${1}"
OUT_FILE="${2}"

if [ -z "${OUT_FILE}" ]
then
  OUT_FILE="${IN_FILE}.wav"
fi

ffmpeg -i "${IN_FILE}" -f wav -c:a copy "${OUT_FILE}"
