#!/bin/bash

set -e

if [ "$#" -lt "1" ]; then
	SCRIPT_NAME=$(basename "${0}")
	echo "Converts a video file into a new version on the border of strong compression and minimal visual difference."
	exit 1
fi

OUT_FILE="${2}"

if [ ! -f "${1}" ]
then
  echo "Not a file!"
  exit -1
fi

if [ -z "${OUT_FILE}" ]; then
  OUT_FILE="${1}.hevc.preset-medium.remote.crf18.mp4"
fi

if [ -f "${OUT_FILE}" ]; then
  echo "${OUT_FILE} already exists."
  exit 1
fi

rsync "${1}" "Galois.local:/Users/lgarron/Public/video-processing/${1}"
ssh Galois.local "archive-h265-crf18 /Users/lgarron/Public/video-processing/${1}"
rsync "Galois.local:/Users/lgarron/Public/video-processing/${1}.hevc.preset-medium.crf18.mp4" "${OUT_FILE}"

# nice -n 20 \
# 	ffmpeg \
#     -i "${1}" \
#     -c:v libx265 \
#     -preset medium \
#     -crf 18 \
#     -c:a aac \
#     -b:a 128k \
#     "${OUT_FILE}" \
#   && touch -r "${1}" "${OUT_FILE}"
