#!/usr/bin/env fish

set COMMAND $argv[1]
set PAM_SUDO_FILE "/private/etc/pam.d/sudo"

function show_help
  set SCRIPT_NAME (basename (status -f))
  echo "Usage: $SCRIPT_NAME [enable/disable/status]"
  echo ""
  echo "Enable Touch ID for sudo commands in shells by adding `pam_tid.so` to `$PAM_SUDO_FILE`."
  exit
end

function show_current
  echo "[$PAM_SUDO_FILE] Lines currently containing `pam_tid.so`:"
  cat $PAM_SUDO_FILE | grep "pam_tid\.so" ; or echo "(none)"
  echo "----------------"
end

if [ "$COMMAND" = "status" ]
  show_original
else if [ "$COMMAND" = "enable" ]
  show_original
  echo "Ensuring `auth sufficient pam_tid.so` entry."
  echo "May require `sudo` auth itself."
  cat $PAM_SUDO_FILE | grep pam_tid.so > /dev/null ; or \
    sudo sed -i "" "1,/.so/s/^auth/auth       sufficient     pam_tid.so\nauth/" $PAM_SUDO_FILE # Touch ID sudo
else if [ "$COMMAND" = "disable" ]
  show_original
  echo "Deleting any `auth sufficient pam_tid.so` entry."
  echo "May require `sudo` auth itself."
  sudo sed -i "" "/^auth  *sufficient  *pam_tid\.so\$/d" $PAM_SUDO_FILE
else
  show_help
end

echo "----------------"
echo "[$PAM_SUDO_FILE] Lines now containing `pam_tid.so`:"
cat $PAM_SUDO_FILE | grep "pam_tid\.so" ; or echo "(none)"
