#!/usr/bin/env fish

# Uses https://github.com/avibrazil/RDM
# Thanks to https://apple.stackexchange.com/a/368166

if [ "scale = 2.0" = (/Applications/RDM.app/Contents/MacOS/SetResX -ld | grep -o "scale = \d\.\d") ]
  set NEW_RES "1.0"
else
  set NEW_RES "2.0"
end
/Applications/RDM.app/Contents/MacOS/SetResX -s $NEW_RES
