#!/usr/bin/env fish

set TEMP_DIR (mktemp -d)
cd $TEMP_DIR
echo "{}" > package.json
npm install -- $argv

echo "--------"
echo -n "Number of files: "
set_color --bold
find node_modules -type f | ls | wc -l | tr -d " "
set_color normal

echo "--------"
echo "Number of bytes: "
du -sh node_modules

rm -rf $TEMP_DIR
